# Generated by Django 4.2.7 on 2024-07-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usercalendar_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlecredentials",
            old_name="access_token_expiry",
            new_name="expiry",
        ),
    ]
