# Generated by Django 4.2.7 on 2024-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecredentials",
            name="access_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
