# Generated by Django 4.2.7 on 2024-06-25 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("min_duration", models.IntegerField(default=30)),
                ("max_duration", models.IntegerField(default=60)),
                (
                    "category",
                    models.CharField(
                        choices=[("personal", "Personal"), ("work", "Work")],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("every day", "Every day"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("times_per_period", models.SmallIntegerField(default=1)),
                ("ideal_days", models.JSONField(blank=True, null=True)),
                ("ideal_time", models.TimeField(default=datetime.time(8, 0))),
                ("starting", models.DateField(default=datetime.date.today)),
                ("ending", models.DateField(blank=True, null=True)),
                ("visibility", models.CharField(default="Busy", max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("custom_hours", models.JSONField(blank=True, null=True)),
                (
                    "hours",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="planner.hours",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "habit",
            },
        ),
    ]
