# Generated by Django 4.2.7 on 2024-06-19 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default=("high", "High"),
                    ),
                ),
                ("min_duration", models.IntegerField(default=30)),
                ("max_duration", models.IntegerField(default=60)),
                (
                    "category",
                    models.CharField(
                        choices=[("personal", "Personal"), ("work", "Work")],
                        default=("personal", "Personal"),
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("every day", "Every day"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default=("weekly", "Weekly"),
                    ),
                ),
                ("times_per_period", models.SmallIntegerField(default=1)),
                ("ideal_days", models.JSONField(blank=True, null=True)),
                ("ideal_time", models.TimeField(default=datetime.time(8, 0))),
                ("starting", models.DateField(default=datetime.date.today)),
                ("ending", models.DateField(blank=True, null=True)),
                ("visibility", models.CharField(default="Busy", max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "habit",
            },
        ),
    ]
