# Generated by Django 4.2.7 on 2024-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="название"
                    ),
                ),
                ("duration", models.JSONField()),
                ("schedule", models.JSONField()),
                ("ideal_time", models.TimeField(blank=True, null=True)),
                ("private", models.BooleanField(default=True)),
            ],
        ),
    ]
