# Generated by Django 4.2.7 on 2024-06-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="ideal_days",
        ),
    ]
