# Generated by Django 4.2.7 on 2024-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="habit",
            table="habit",
        ),
    ]
