# Generated by Django 4.2.7 on 2024-06-13 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="ideal_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name="habit",
            name="schedule",
            field=models.JSONField(
                default={"period": ("weekly", "Weekly"), "times": "1"},
                verbose_name="period & times per period",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="starting",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
