# Generated by Django 4.2.7 on 2024-07-16 13:17

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("every day", "Every day"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default=utils.Period["WEEKLY"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default=utils.Priority["HIGH"],
                max_length=20,
            ),
        ),
    ]
