# Generated by Django 4.2.7 on 2024-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_ideal_time_alter_habit_schedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="schedule",
        ),
        migrations.AddField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("every day", "Every day"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default=("weekly", "Weekly"),
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="times_per_period",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="habit",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default=("high", "High"),
                max_length=8,
            ),
        ),
    ]
