# Generated by Django 4.2.7 on 2024-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habit_schedule_habit_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[("personal", "Personal"), ("work", "Work")],
                default=("personal", "Personal"),
                max_length=10,
            ),
        ),
    ]
