# Generated by Django 4.2.7 on 2024-06-19 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default=("high", "High"),
                    ),
                ),
                ("time_needed", models.IntegerField(default=60)),
                ("min_duration", models.IntegerField(default=0)),
                ("max_duration", models.IntegerField(default=0)),
                ("due_date", models.DateField(blank=True)),
                ("schedule_after", models.DateField(default=datetime.date.today)),
                ("visibility", models.CharField(default="Busy", max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "task",
            },
        ),
    ]
