# Generated by Django 4.2.7 on 2024-07-20 09:24

import datetime
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=utils.Priority['HIGH'], max_length=20)),
                ('duration', models.IntegerField(default=60)),
                ('min_duration', models.IntegerField(default=None, null=True)),
                ('max_duration', models.IntegerField(default=None, null=True)),
                ('schedule_after', models.DateTimeField(default=datetime.datetime(2024, 7, 20, 12, 24, 23, 680534), null=True)),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 23, 12, 24, 23, 680534))),
                ('time_spent', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('private', models.BooleanField(default=True)),
                ('visibility', models.CharField(default='Busy', max_length=200, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
