# Generated by Django 4.2.7 on 2024-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="max_duration",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="task",
            name="min_duration",
            field=models.IntegerField(default=None),
        ),
    ]
