# Generated by Django 4.2.7 on 2024-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_max_duration_alter_task_min_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="max_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="min_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default=("high", "High"),
                max_length=8,
            ),
        ),
    ]
