# Generated by Django 4.2.7 on 2024-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_time_spent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="time_needed",
            new_name="duration",
        ),
        migrations.AddField(
            model_name="task",
            name="private",
            field=models.BooleanField(default=True),
        ),
    ]
