# Generated by Django 4.2.7 on 2024-07-16 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_time_needed_task_duration_task_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="schedule_after",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 16, 11, 47, 7, 398967, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="visibility",
            field=models.CharField(default="Busy", max_length=200, null=True),
        ),
    ]
