# Generated by Django 4.2.7 on 2024-07-16 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_schedule_after_alter_task_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="schedule_after",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 16, 11, 51, 51, 384608, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
