# Generated by Django 4.2.7 on 2024-07-16 13:17

import datetime
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_max_duration_alter_task_min_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default=utils.Priority["HIGH"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="schedule_after",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 16, 21, 17, 41, 946766), null=True
            ),
        ),
    ]
