# Generated by Django 4.2.7 on 2024-07-20 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_due_date_alter_task_schedule_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 7, 23, 15, 40, 52, 576378)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="max_duration",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="min_duration",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="schedule_after",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 20, 15, 40, 52, 576378), null=True
            ),
        ),
    ]
